# -*- coding: utf-8 -*-

import shelve
import sys

def init():
	db = shelve.open('rocks')
	db['Iggy Pop'] = {'photo': 'IggyPop.jpg', 'albums': ['The Idiot',
					  'Lust for Life',
					  'New Values',
					  'Soldier',
					  'Party',
					  'Zombie Birdhouse',
					  'Blah Blah Blah',
					  'Instinct',
					  'Brick by Brick',
					  'American Caesar',
					  'Naughty Little Doggie',
					  'Avenue B',
					  "Beat ’Em Up",
					  'Skull Ring'
					  'Preliminaires',
					  'Après']}
	db['David Bowie'] = {'photo': 'DavidBowie.jpg', 'albums': ['David Bowie',
						 'Space Oddity',
						 'The Man Who Sold the World',
						 'Hunky Dory',
						 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
						 'Aladdin Sane',
						 'Pin Ups',
						 'Diamond Dogs',
						 'Young Americans',
						 'Station to Station',
						 'Low',
						 'Heroes',
						 'Lodger',
						 'Scary Monsters (and Super Creeps)',
						 "Let’s Dance",
						 'Tonight',
						 'Never Let Me Down',
						 'Tin Machine',
						 'Tin Machine II',
						 'Black Tie White Noise',
						 '1.Outside',
						 'Earthling',
						 "‘hours…’",
						 'Heathen',
						 'Reality',
						 'The Next Day']}
	db['Queen'] = {'photo': 'Queen.jpg', 'albums': ['Queen',
				   'Queen II',
				   'Sheer Heart Attack',
				   'A Night at the Opera',
				   'A Day at the Races',
				   'News of the World',
				   'Jazz',
				   'The Game',
				   'Flash Gordon',
				   'Hot Space',
				   'The Works',
				   'A Kind of Magic',
				   'The Miracle',
				   'Innuendo',
				   'Made in Heaven',
				   'The Cosmos Rocks']}
	db['King Crimson'] = {'photo': 'KingCrimson.jpg', 'albums': ['In the Court of the Crimson King',
						  'In the Wake of Poseidon',
						  'Lizard',
						  'Islands',
						  'Larks’ Tongues in Aspic',
						  'Starless and Bible Black',
						  'Red',
						  'Discipline',
						  'Beat',
						  'Three of a Perfect Pair',
						  'VROOOM',
						  'THRAK',
						  'The ConstruKction of Light',
						  'The Power to Believe']}
	db['The Velvet Underground'] = {'photo': 'TheVelvetUnderground.jpg', 'albums': ['The Velvet Underground and Nico',
									'White Light/White Heat',
									'The Velvet Underground',
									'Loaded ',
									'Squeeze']}
	db['Joy Division'] = {'photo': 'JoyDivision.jpg', 'albums': ['Unknown Pleasures',
						  'Closer']}
	db['The Beatles'] = {'photo': 'TheBeatles.jpg', 'albums': ['Please Please Me',
						 'With The Beatles',
						 'A Hard Day’s Night',
						 'Beatles For Sale',
						 'Help!',
						 'Rubber Soul',
						 'Revolver',
						 'Sgt. Pepper’s Lonely Hearts Club Band',
						 'Magical Mystery Tour',
						 'The Beatles',
						 'Yellow Submarine',
						 'Abbey Road',
						 'Let It Be']}
	db.close()

if __name__ == "__main__":
	init()
